In [1]:
import pandas as pd
import numpy as np

In [2]:
# importing train dataaset

data1=pd.read_csv("SalaryData_Train.csv")
data1.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [3]:
# importing test dataaset

data2=pd.read_csv("SalaryData_Test.csv")
data2.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [10]:
# Convering values of "salary" column with use of "convert" function

convert = {' >50K': 1, ' <=50K': 2}
data2 = data2.replace({'Salary': convert})

In [12]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

columns=["workclass","education","maritalstatus","occupation","relationship","race","sex","native"]

In [13]:
for i in columns:
    data2[i]= label_encoder.fit_transform(data2[i])
    
data2

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            40   
1                 0     4    1            0            0            50   
2                 0     4    1            0            0            40   
3                 0     2    1         7688            0            40   
4                 1     4    1            0            0            30   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            40   
15056             1     4    0            0            0            36   
15057             0     4    1            0            0            50   
15058             3     1    1         5455            0            40   
15059             0     4    1            0            0            60   

       native  Salary  
0          37       2  
1          37       2  
2          37       1  
3          37       1  
4          37       2  
...       ...     ...  
15055      37       2  
15056      37       2  
15057      37       2  
15058      37       2  
15059      37       1  

[15060 rows x 14 columns]

In [14]:
convert = {' >50K': 1, ' <=50K': 2}
data1 = data1.replace({'Salary': convert})

In [15]:
for i in columns:
    data1[i]= label_encoder.fit_transform(data1[i])
    
data1

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1         2174            0            40   
1                 0     4    1            0            0            13   
2                 1     4    1            0            0            40   
3                 0     2    1            0            0            40   
4                 5     2    0            0            0            40   
...             ...   ...  ...          ...          ...           ...   
30156             5     4    0            0            0            38   
30157             0     4    1            0            0            40   
30158             4     4    0            0            0            40   
30159             3     4    1            0            0            20   
30160             5     4    0        15024            0            40   

       native  Salary  
0          37       2  
1          37       2  
2          37       2  
3          37       2  
4           4       2  
...       ...     ...  
30156      37       2  
30157      37       1  
30158      37       2  
30159      37       2  
30160      37       1  

[30161 rows x 14 columns]

# Performing Naive Bayes Algorithm with differnet Models(conditions)

In [17]:
x_train = data1.iloc[:,0:13]
y_train = data1.iloc[:,13]
x_test = data2.iloc[:,0:13]
y_test = data2.iloc[:,13]

### (1) GaussianNB
GaussianNB implements the Gaussian Naive Bayes algorithm for classification.

In [18]:
from sklearn.naive_bayes import GaussianNB
clsfrgnb = GaussianNB()   # clsfrgnb = claasification with Gussian Naive Bayes

In [19]:
# Model Making

model1=clsfrgnb.fit(x_train, y_train)

In [20]:
# Prediction with x_test

y_pred_gnb = model1.predict(x_test)  # gnb=gausian naive bayes

In [21]:
y_pred_gnb

array([2, 2, 2, ..., 2, 1, 2], dtype=int64)

In [30]:
print ("Accuracy",np.mean(y_pred_gnb==y_test.values.flatten())*100)

Accuracy 79.46879150066401


In [22]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_gnb)   #Confusion matrix

array([[ 1209,  2491],
       [  601, 10759]], dtype=int64)

In [23]:
pd.crosstab(y_test.values.flatten(),clsfrgnb)

col_0  GaussianNB()
row_0              
1              3700
2             11360

### (2) - MultinomialNB

MultinomialNB implements the naive Bayes algorithm for multinomially distributed data, and is one of the two classic naive Bayes variants used in text classification (where the data are typically represented as word vector counts, although tf-idf vectors are also known to work well in practice).

In [68]:
from sklearn.naive_bayes import MultinomialNB
clsfrmnnb = MultinomialNB()   # clsfrgnb = claasification with Multinominal Naive Bayes

In [69]:
model2=clsfrmnnb.fit(x_train, y_train)
model2

MultinomialNB()

In [70]:
y_pred_mnnb = model2.predict(x_test)   # # mnb=Multinominal naive bayes

In [71]:
# Confusion Metrix

confusion_matrix(y_test, y_pred_mnnb)

array([[  780,  2920],
       [  469, 10891]], dtype=int64)

In [72]:
pd.crosstab(y_test.values.flatten(),clsfrmnnb)

col_0  MultinomialNB()
row_0                 
1                 3700
2                11360

In [73]:
print ("Accuracy",np.mean(y_pred_mnb==y_test.values.flatten()))

Accuracy 0.7749667994687915


In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_mnb)*100

77.49667994687915

In [32]:
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import CategoricalNB

### 3 ComplementNB

ComplementNB implements the complement naive Bayes (CNB) algorithm.

In [75]:
clsfrCLnb = ComplementNB()

In [76]:
model3=clsfrCLnb.fit(x_train, y_train)

In [77]:
y_pred_CLnb = model3.predict(x_test) 

In [78]:
# Confusion Metrix

confusion_matrix(y_test, y_pred_CLnb)

array([[  780,  2920],
       [  469, 10891]], dtype=int64)

In [79]:
pd.crosstab(y_test.values.flatten(),clsfrCLnb)

col_0  ComplementNB()
row_0                
1                3700
2               11360

In [80]:
print ("Accuracy",np.mean(y_pred_CLnb==y_test.values.flatten()))

Accuracy 0.7749667994687915


### 4 BernoulliNB

BernoulliNB implements the naive Bayes training and classification algorithms

In [57]:
clsfrBnb = BernoulliNB()

In [58]:
model4=clsfrBnb.fit(x_train, y_train)

In [59]:
y_pred_Bnb = model4.predict(x_test) 

In [60]:
# Confusion Metrix

confusion_matrix(y_test, y_pred_Bnb)

array([[2690, 1010],
       [3080, 8280]], dtype=int64)

In [62]:
print ("Accuracy",np.mean(y_pred_Bnb==y_test.values.flatten())*100)

Accuracy 72.84196547144755


### 5 CategoricalNB

CategoricalNB implements the categorical naive Bayes algorithm for categorically distributed data

In [88]:
clsfrCALnb = CategoricalNB()

In [89]:
model4=clsfrCALnb.fit(x_train, y_train)

In [90]:
y_pred_CALnb = model4.predict(x_test) 

In [91]:
# Confusion Metrix

confusion_matrix(y_test, y_pred_CALnb)

array([[ 2426,  1274],
       [  885, 10475]], dtype=int64)

In [92]:
print ("Accuracy",np.mean(y_pred_CALnb==y_test.values.flatten())*100)

Accuracy 85.66401062416999


In [101]:
seed = 7
models = []
models.append(('GNB', GaussianNB()))
models.append(('MNB', MultinomialNB()))
models.append(('CPTNB', ComplementNB()))
models.append(('CATNB', CategoricalNB()))
models.append(('BALNB', BernoulliNB()))


In [102]:
results = []
names = []
scoring = 'accuracy'

In [103]:
import warnings
warnings.filterwarnings('ignore')

In [104]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

for name, model in models:
    kfold = KFold(n_splits=10, random_state=seed,shuffle = True)
    cv_results = cross_val_score(model, x_train, y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

GNB: 0.795498 (0.007394)
MNB: 0.772919 (0.008042)
CPTNB: 0.772919 (0.008042)
CATNB: nan (nan)
BALNB: 0.725573 (0.005228)
